server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8099/eureka/

spring:
  cloud:
    gateway:
      routes:
      - id: customer
        uri: lb://CUSTOMER-SERVICE
        predicates:
        - Path=/customer/**
      - id: product
        uri: lb://PRODUCT-SERVICE
        predicates:
        - Path=/product/**
      - id: shopping
        uri: lb://SHOPPING-SERVICE
        predicates:
        - Path=/invoice/**