server:
  port: 8092

spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    platform: h2
    username: sa
    password:

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: false
        format_sql: false
    defer-datasource-initialization: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8099/eureka/
      
#Activar actuator
management:
  endpoints:
    web:
      exposure:
        include: "*"