server:
  port: 8091
spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-admin:eureka-pass@localhost:8099/eureka/

#Activar actuator
management:
  endpoints:
    web:
      exposure:
        include: "*"