server:
  port: 8093

spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    platform: h2
    username: sa
    password:

  # JPA / HIBERNATE
  jpa:
    defer-datasource-initialization: true
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: false
        format_sql: false
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-admin:eureka-pass@localhost:8099/eureka/

#Activar actuator
management:
  endpoints:
    web:
      exposure:
        include: "*"

#Feign Config
feign:                          
  circuitbreaker:               
    enabled: true               
    alphanumeric-ids:           
      enabled: true             

#Circuit Breaker Config
resilience4j:                   
  circuitbreaker:               
    instances:                  
      customer-service:
        registerHealthIndicator: true
        slidingWindowSize: 10
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowType: TIME_BASED
        minimumNumberOfCalls: 20
        waitDurationInOpenState: 50s
        failureRateThreshold: 50
        eventConsumerBufferSize: 10

