server:
  port: 8093

spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    platform: h2
    username: sa
    password:

  # JPA / HIBERNATE
  jpa:
    defer-datasource-initialization: true
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: false
        format_sql: false
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-admin:eureka-pass@localhost:8099/eureka/

# Configuracion para Actuator
management:
  health:
    circuitbreakers:
      # Enable circuit breaker auto configuration
      enabled: true
  endpoints:
    web:
      exposure:
        # * to expose all enpoints inside actuator
        include: "*"
  endpoint:
    health:
      # When to show health details
      show-details: always

#Resilience4j
resilience4j:
  circuitbreaker:
    instances:
      invoice:
        # Register/See states of cributi breaker: open -> closed
        register-health-indicator: true
        # How much size is added for the events
        event-consumer-buffer-size: 10
        # How to handle requests number/time for close/open the circuit
        sliding-window-type: count-based
        # Number of request to take into accout when deciding to open/close circuit
        sliding-window-size: 5
        # Percentage of request from window size that need to fail, to close the circuit
        failure-rate-threshold: 50
        # Time to wait from Open state before changing into half-open
        wait-duration-in-open-state: 5s
        permitted-number-of-calls-in-half-open-state: 3
        automatic-transition-from-open-to-half-open-enabled: true

#Feign Config
feign:                          
  circuitbreaker:               
    enabled: true               
    alphanumeric-ids:           
      enabled: true             
